version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  reviewers:
  - gabrieltanchen
  ignore:
  - dependency-name: sass
    versions:
    - 1.32.10
    - 1.32.5
    - 1.32.6
    - 1.32.8
  - dependency-name: eslint
    versions:
    - 7.20.0
    - 7.22.0
    - 7.23.0
    - 7.24.0
  - dependency-name: ember-template-lint
    versions:
    - 2.17.0
    - 2.18.0
    - 3.1.1
    - 3.2.0
  - dependency-name: ember-source
    versions:
    - 3.24.1
    - 3.25.0
    - 3.25.3
    - 3.26.0
  - dependency-name: ember-cli-htmlbars
    versions:
    - 5.3.2
    - 5.4.0
    - 5.6.0
    - 5.6.2
    - 5.6.4
    - 5.6.5
    - 5.7.0
  - dependency-name: ember-power-select
    versions:
    - 4.1.3
  - dependency-name: ember-cli
    versions:
    - 3.25.0
    - 3.25.1
  - dependency-name: socket.io
    versions:
    - 2.4.1
  - dependency-name: eslint-plugin-ember
    versions:
    - 10.1.2
  - dependency-name: ember-data
    versions:
    - 3.24.0
