---
version: 2
checks:
  file-lines:
    config:
      threshold: 1000
  method-complexity:
    enabled: false
  method-lines:
    config:
      threshold: 250
plugins:
  eslint:
    enabled: true
    channel: "eslint-4"
    config:
      extensions:
        - .js
  sass-lint:
    enabled: true
    channel: "beta"
ratings:
  paths:
  - app/**
  - "**.js"
exclude_paths:
- config/
